### ISSUE TITLE
handleEvent errors

### ISSUE THREAD

**Issue by sharkooon** [chrisShick/CakePHP3-HtmlPurifier#1]
Latest version got error using cakephp 3.1:

Warning (4096): Argument 2 passed to chrisShick\CakePHP3HtmlPurifier\Model\Behavior\HtmlPurifierBehavior::handleEvent() must implement interface Cake\Datasource\EntityInterface, instance of ArrayObject given, called in /Volumes/Dev/htdocs/gecondoleerd/vendor/cakephp/cakephp/src/Event/EventManager.php on line 389 and defined [ROOT/vendor/chrisshick/cakephp3-html-purifier/src/Model/Behavior/HtmlPurifierBehavior.php, line 93]

**Comment by chrisShick** [comment]
Hey @designway,

I apologize for the delay in responding. Do you have your example code that you are using that causes this issue to pop up? 
Right now, the HtmlPurifier requires that you pass and entity and it appears an array object is being passed.
