### ISSUE TITLE
CakePHP 4 Support

### ISSUE THREAD

**Issue by josephshanak** [chrisShick/CakePHP3-HtmlPurifier#10]
I am currently using this plugin in a CakePHP3 application that is preparing to upgrade to CakePHP 4, and I would like to know what your plans are for maintaining this plugin now that CakePHP 4 is out. Are there plans on updating this plugin to support CakePHP 4?

**Comment by chrisShick** [comment]
Hi @josephshanak, I will be taking a look at updating this to Cake 4.x this week!

**Comment by smap9** [comment]
Hey @chrisShick is there anything new here?

**Comment by chrisShick** [comment]
@smap9 not sure if you’ve seen the new release a while back. I will be closing this ticket now.
