### ISSUE TITLE
HTML5 support

### ISSUE THREAD

**Issue by ypnos-web** [chrisShick/CakePHP3-HtmlPurifier#5]
In my own usage of the plugin I added support for some HTML5 elements based on https://github.com/xemlock/htmlpurifier-html5

Instead of depending on that work, which seems rather unmaintained(?), I added relevant code to the behavior directly.

Would you be interested in merging such optional functionality into your plugin? In that case I could refactor my work and prepare a pull request.

**Comment by chrisShick** [comment]
That would definitely be a great addition!

**Comment by ypnos-web** [comment]
Did you get a chance to look at #6?

**Comment by chrisShick** [comment]
@ypnos-web, sorry man! The holidays got a little hectic. I have only had the chance to glance at it. I will look more thoroughly tonight
