### ISSUE TITLE
Migration to cakephp 3.6

### ISSUE THREAD

**Issue by rudy1976s** [chrisShick/CakePHP3-HtmlPurifier#7]
Hi Chris
thank you for your plugin: I have recently upgraded cakephp to 3.6 which introduced a lot of deprecation: actually the plugin no longer works:  do you plan to release a compatible cake 3.6 release ?

Thank you again

Rudy

**Comment by chrisShick** [comment]
@rudy1976s I will be creating a compatible release in the next few days.

**Comment by Kitcat711** [comment]
Hi Chris,
I thank you for your plugin too. Just wonder if you still plan to create a compatible release.
Thank your for your answer.
Kitcat

**Comment by chrisShick** [comment]
@Kitcat711 I am fixing the travis-ci issues and then a release should be ready :)

**Comment by chrisShick** [comment]
@Kitcat711 @rudy1976s I have updated the code to support 3.6

Let me know if you have any issues.
